version: '3'

services:
  db:
    image: postgres:latest
    container_name: lutenix_db
    restart: always
    environment:
      POSTGRES_DB: lutenix_db
      POSTGRES_USER: lutenix
      POSTGRES_PASSWORD: lutenix
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: lutenix_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: